name: Docker Image Build

on:
  repository_dispatch:
    types: [push-dockerfile]
  
permissions:
      contents: read
      id-token: write

env:  
 PROJECT_ID: project-06cede75-fb8e-4bfb-984
 REGION: asia-south1
 REPO: repo-app
 IMAGE: ${{ github.event.client_payload.app_names}}
 
jobs:
 # ── 1. Build and Push Docker image ──────────────────────────────────────────
  build:
    name: Build-${{ github.event.client_payload.app_names }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repo
        uses: actions/checkout@v4
        with:
         repository: reenipaul16/python-app
         token: ${{ secrets.CI_PAT }}
         path: app

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/489414658403/locations/global/workloadIdentityPools/github/providers/application'
          service_account: 'sa-application@project-06cede75-fb8e-4bfb-984.iam.gserviceaccount.com'

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # - name: Create Artifact Registry repo (if not exists)
      #   run: |
      #     gcloud artifacts repositories create $REPO \
      #       --repository-format=docker \
      #       --location=$REGION \
      #       --project=$PROJECT_ID || true

      - name: Verify authentication
        run: |
          gcloud auth list
          gcloud config list

      - name: Build & push image
        working-directory: app
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          echo $TIMESTAMP

          IMAGE_URI=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$TIMESTAMP
          echo $IMAGE_URI

          docker build -f dockerfiles/Dockerfile-$IMAGE -t "$IMAGE_URI" .

          docker push $IMAGE_URI
# docker push $IMAGE_URI
#docker tag $IMAGE_URI $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest

          
