name: Deploy Helm to GKE

on:
  repository_dispatch:
    types: [helm-deploy]
  
permissions:
      contents: read
      id-token: write

env:
   HELM_DIR: ${{ github.event.client_payload.helm_dir }}
   REPO_URL: ${{ github.event.client_payload.repo_url }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/489414658403/locations/global/workloadIdentityPools/github/providers/application'
          service_account: 'sa-application@project-06cede75-fb8e-4bfb-984.iam.gserviceaccount.com'

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: 'as-cluster'
          location: 'asia-south1-a'

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Extract Helm details
        id: helm
        run: |
          echo "$REPO_URL"
          CHART_DIR=$(dirname "${HELM_DIR}")

          RELEASE_NAME=$(echo "${CHART_DIR}" | cut -d'/' -f1)

          echo "chart_dir=${CHART_DIR}" >> "$GITHUB_OUTPUT"
          echo "release_name=${RELEASE_NAME}" >> "$GITHUB_OUTPUT"

          echo "Chart Dir   : ${CHART_DIR}"
          echo "Release Name: ${RELEASE_NAME}"

      - name: Deploy
        run: |
          echo "Chart Dir   : ${{ steps.helm.outputs.release_name }}"
          echo "Release Name: ${{ steps.helm.outputs.chart_dir }}"
          helm upgrade --install "${{ steps.helm.outputs.release_name }}" "${{ steps.helm.outputs.chart_dir }}" \
          --rollback-on-failure \